# Generated by Django 4.2.16 on 2024-11-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated_on',
        ),
    ]
